<div class="p-6 space-y-6 border bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900 rounded-2xl border-blue-700/20">
    @if(session()->has('success'))<div class="p-3 text-sm text-green-400 border rounded-lg bg-green-500/20 border-green-500/50">{{ session('success') }}</div>@endif
    <div class="grid gap-6 md:grid-cols-2">
        <div><h3 class="flex items-center gap-2 mb-4 text-xl font-bold text-white"><svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/></svg>Find Friends</h3>
            <div class="space-y-3">
                <input type="text" wire:model.live="searchQuery" placeholder="Search users by name or @username..." class="w-full px-4 py-2 text-white placeholder-gray-500 transition border rounded-lg bg-slate-700 border-blue-700/20 focus:border-blue-700 focus:outline-none">
                @if($filteredUsers->isNotEmpty())<div class="space-y-2 overflow-y-auto max-h-96">@foreach($filteredUsers as $user)<div class="flex items-center justify-between p-3 rounded-lg bg-slate-700/50"><div class="flex items-center flex-1 gap-3"><img src="{{ $user->profile_photo_path ? asset('storage/' . $user->profile_photo_path) : 'https://ui-avatars.com/api/?name=' . urlencode($user->name) . '&background=8b5cf6&color=fff' }}" alt="{{ $user->name }}" class="object-cover w-10 h-10 rounded-full"><div><p class="text-sm font-semibold text-white">{{ $user->name }}</p><p class="text-xs text-gray-400">{{ '@' . ($user->username ?? strtolower(str_replace(' ', '', $user->name))) }}</p></div></div><button wire:click="sendContactRequest({{ $user->id }})" class="px-3 py-1 text-sm font-semibold text-white transition rounded-full bg-gradient-to-r from-blue-700 to-black hover:shadow-lg">+ Add</button></div>@endforeach</div>@endif
            </div>
        </div>
        <div><h3 class="flex items-center gap-2 mb-4 text-xl font-bold text-white"><svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg>Pending Requests ({{ $contactRequests->count() }})</h3>
            @forelse($contactRequests as $request)<div class="flex items-center justify-between p-3 mb-3 rounded-lg bg-slate-700/50"><div class="flex items-center flex-1 gap-3"><img src="{{ $request->user->profile_photo_path ? asset('storage/' . $request->user->profile_photo_path) : 'https://ui-avatars.com/api/?name=' . urlencode($request->user->name) . '&background=8b5cf6&color=fff' }}" alt="{{ $request->user->name }}" class="object-cover w-10 h-10 rounded-full"><div><p class="text-sm font-semibold text-white">{{ $request->user->name }}</p><p class="text-xs text-gray-400">{{ '@' . ($request->user->username ?? strtolower(str_replace(' ', '', $request->user->name))) }}</p></div></div><div class="flex gap-2"><button wire:click="acceptContactRequest({{ $request->user_id }})" class="px-2 py-1 text-xs font-semibold text-green-400 transition rounded-lg bg-green-500/20 hover:bg-green-500/30">✓ Accept</button><button wire:click="refuseContactRequest({{ $request->user_id }})" class="px-2 py-1 text-xs font-semibold text-red-400 transition rounded-lg bg-red-500/20 hover:bg-red-500/30">✕ Refuse</button></div></div>@empty<p class="text-sm text-gray-400">No pending requests</p>@endforelse
        </div>
    </div>
    <div><h3 class="flex items-center gap-2 mb-4 text-xl font-bold text-white"><svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg>My Contacts ({{ $myContacts->count() }})</h3>
        <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">@forelse($myContacts as $contact)<div class="p-4 border rounded-lg bg-gradient-to-br from-slate-700 to-slate-800 border-blue-700/20"><div class="flex items-start justify-between mb-3"><img src="{{ $contact->profile_photo_path ? asset('storage/' . $contact->profile_photo_path) : 'https://ui-avatars.com/api/?name=' . urlencode($contact->name) . '&background=8b5cf6&color=fff' }}" alt="{{ $contact->name }}" class="object-cover w-12 h-12 rounded-full"><button wire:click="blockUser({{ $contact->id }})" class="text-sm text-gray-400 transition hover:text-red-400">🚫</button></div><h4 class="font-bold text-white">{{ $contact->name }}</h4><p class="mb-3 text-xs text-gray-400">{{ '@' . ($contact->username ?? strtolower(str_replace(' ', '', $contact->name))) }}</p><button class="w-full px-3 py-2 text-sm font-semibold text-white transition rounded-lg bg-gradient-to-r from-blue-700 to-black hover:shadow-lg">💬 Message</button></div>@empty<div class="py-8 text-center text-gray-400 col-span-full"><p>No contacts yet. Start sending requests!</p></div>@endforelse</div>
    </div>
</div>

